Refactored devtool

diff --git a/tools/devtool b/tools/devtool
--- a/tools/devtool
+++ b/tools/devtool
@@ -18,14 +18,8 @@ VC_TOOLS_DIR=$(cd "$(dirname "$0")" && pwd)
 # Full path to the Valcan sources dir on the host.
 VC_ROOT_DIR=$(cd "${VC_TOOLS_DIR}/.." && pwd)
 
-# Full path to the build dir on the host.
-VC_C_BUILD_DIR="${VC_ROOT_DIR}/build"
-
 # Full path to devctr dir on the host.
 VC_DEVCTR_DIR="${VC_ROOT_DIR}/tools/devctr"
-
-# Path to the linux kernel directory on the host.
-KERNEL_DIR="${VC_ROOT_DIR}/.kernel"
 
 # Full path to the Firecracker sources dir, as bind-mounted in the container.
 CTR_VC_ROOT_DIR="/valcan"
@@ -91,6 +85,33 @@ ensure_build_dir() {
     done
 }
 
+# Run a command and retry multiple times if it fails. Once it stops
+# failing return to normal execution. If there are "retry count"
+# failures, set the last error code.
+# $1 - command
+# $2 - retry count
+# $3 - sleep interval between retries
+#
+retry_cmd() {
+    command=$1
+    retry_cnt=$2
+    sleep_int=$3
+
+    {
+        $command
+    } || {
+        # Command failed, substract one from retry_cnt
+        retry_cnt=$((retry_cnt - 1))
+
+        # If retry_cnt is larger than 0, sleep and call again
+        if [ "$retry_cnt" -gt 0 ]; then
+            echo "$command failed, retrying..."
+            sleep "$sleep_int"
+            retry_cmd "$command" "$retry_cnt" "$sleep_int"
+        fi
+    }
+}
+
 # Check if Docker is available and exit if it's not.
 # Upon returning from this call, the caller can be certain Docker is available.
 #
@@ -119,8 +140,6 @@ ensure_devctr() {
     # We depend on having Docker present.
     ensure_docker
 
-echo "docker images -q $DEVCTR_IMAGE | wc -l) -gt 0"
-
     # Check if we have the container image available locally. Attempt to
     # download it, if we don't.
     [[ $(docker images -q "$DEVCTR_IMAGE" | wc -l) -gt 0 ]] || {
@@ -129,16 +148,56 @@ echo "docker images -q $DEVCTR_IMAGE | wc -l) -gt 0"
 
         # Run docker pull 5 times in case it fails - sleep 3 seconds
         # between attempts
-        retry_cmd "docker pull $DEVCTR_IMAGE" 5 3
+        retry_cmd cmd_build_devctr 5 3
 
-        ok_or_die "Error pulling docker image. Aborting."
+        ok_or_die "Error building docker image. Aborting."
     }
+}
+
+# Prompt the user for confirmation before proceeding.
+# Args:
+#   $1  prompt text.
+#       Default: Continue? (y/n)
+#   $2  confirmation input.
+#       Default: y
+# Return:
+#   exit code 0 for successful confirmation
+#   exit code != 0 if the user declined
+#
+get_user_confirmation() {
+
+    # Pass if running unattended
+    [[ "$OPT_UNATTENDED" = true ]] && return 0
+
+    # Fail if STDIN is not a terminal (there's no user to confirm anything)
+    [[ -t 0 ]] || return 1
+
+    # Otherwise, ask the user
+    #
+    msg=$([ -n "$1" ] && echo -n "$1" || echo -n "Continue? (y/n) ")
+    yes=$([ -n "$2" ] && echo -n "$2" || echo -n "y")
+    say_noln "$msg"
+    read c && [ "$c" = "$yes" ] && return 0
+    return 1
+}
+
+# Fix build/ dir permissions after a privileged container run.
+# Since the privileged container runs as root, any files it creates will be
+# owned by root. This fixes that by recursively changing the ownership of build/
+# to the current user.
+#
+cmd_fix_perms() {
+    # Yes, running Docker to get elevated privileges, just to chown some files
+    # is a dirty hack.
+    # run_devctr \
+    #     -- \
+    #     chown -R "$(id -u):$(id -g)" "$CTR_FC_BUILD_DIR"
+    say "cmd_fix_perms()"
 }
 
 # Builds the development container from its Dockerfile.
 #
 cmd_build_devctr() {
-    echo "cmd_build_devctr()"
     arch=$(uname -m)
     docker_file_name="Dockerfile.$arch"
     build_args="--build-arg TMP_POETRY_DIR=$CTR_POETRY_TMP_DIR"
@@ -146,10 +205,7 @@ cmd_build_devctr() {
     while [ $# -gt 0 ]; do
         case "$1" in
             "-h"|"--help")      { cmd_help; exit 1; } ;;
-            "-n"|"--no-python-package-upgrade")
-                shift
-                build_args="$build_args --build-arg POETRY_LOCK_PATH=tools/devctr/poetry.lock"
-                ;;
+            "-m"|"--MM")        { say "no help yer!"; exit 1; } ;;
             "--")               { shift; break;     } ;;
             *)
                 die "Unknown argument: $1. Please use --help for help."
@@ -158,10 +214,7 @@ cmd_build_devctr() {
         shift
     done
 
-echo "docker build -t $DEVCTR_IMAGE -f $VC_DEVCTR_DIR/$docker_file_name ."
-
     docker build -t "$DEVCTR_IMAGE" -f "$VC_DEVCTR_DIR/$docker_file_name" .
-
 }
 
 # Helper function to run the dev container.
@@ -185,14 +238,6 @@ run_devctr() {
     # the container interactively
     [[ -t 0 ]] && docker_args+=("-i")
     [[ -t 1 ]] && docker_args+=("-t")
-
-    # Try to pass these environments from host into container for network proxies
-    proxies=(http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY)
-    for i in "${proxies[@]}"; do
-        if [[ ! -z ${!i} ]]; then
-            docker_args+=("--env") && docker_args+=("$i=${!i}")
-        fi
-    done
 
     # Finally, run the dev container
     # Use 'z' on the --volume parameter for docker to automatically relabel the
@@ -229,26 +274,14 @@ cmd_shell() {
 
     # Make sure we have what we need to continue.
     ensure_devctr
-    #ensure_build_dir
-
 
     if [[ $privileged = true ]]; then
-    echo "privileged"
         # If requested, spin up a privileged container.
         #
         say "Dropping to a privileged shell prompt ..."
         say "Note: $FC_ROOT_DIR is bind-mounted under $CTR_VC_ROOT_DIR"
         say_warn "You are running as root; any files that get created under" \
             "$CTR_VC_ROOT_DIR will be owned by root."
-
-echo "run_devctr \
-            --privileged \
-            --ulimit nofile=4096:4096 \
-            --ulimit memlock=-1:-1 \
-            --security-opt seccomp=unconfined \
-            --workdir $CTR_VC_ROOT_DIR \
-            -- \
-            bash"
 
         run_devctr \
             --privileged \
@@ -265,7 +298,6 @@ echo "run_devctr \
         #
         cmd_fix_perms
     else
-        echo "NO privileged"
         say "Dropping to shell prompt as user $(whoami) ..."
         say "Note: $FC_ROOT_DIR is bind-mounted under $CTR_VC_ROOT_DIR"
         say_warn "You won't be able to run Firecracker via the jailer," \
@@ -275,16 +307,6 @@ echo "run_devctr \
         [ -w /dev/kvm ] || \
             say_warn "WARNING: user $(whoami) doesn't have permission to" \
                 "access /dev/kvm. You won't be able to run Firecracker."
-
-echo   "run_devctr \
-            --user $(id -u):$(id -g) \
-            --ulimit nofile=4096:4096 \
-            --ulimit memlock=-1:-1 \
-            --device=/dev/kvm:/dev/kvm \
-            --workdir $CTR_VC_ROOT_DIR \
-            --env PS1=$(whoami)@\h:\w\$  \
-            -- \
-            bash --norc"
 
         run_devctr \
             --user "$(id -u):$(id -g)" \
@@ -305,170 +327,23 @@ echo   "run_devctr \
 # Please see `$0 help` for more information.
 #
 cmd_build() {
-
     # By default, we'll build the debug binaries.
     profile="debug"
-    libc="musl"
 
     # Check prerequisites
     ensure_devctr
-    # ensure_build_dir
 
-    say "Starting build ($profile, $libc) ..."
+    say "Build ($profile) ..."
+}
 
-
-
-
-    # Run the cargo build process inside the container.
-    # We don't need any special privileges for the build phase, so we run the
-    # container as the current user/group.
-
-    # Build Firecracker.
-    run_devctr \
-        --user "$(id -u):$(id -g)" \
-        --workdir "$CTR_FC_ROOT_DIR" \
-        ${extra_args} \
-        -- \
-        cargo build \
-            --target-dir "$CTR_CARGO_TARGET_DIR" \
-            "${cargo_args[@]}"
-    ret=$?
-
-    [ $ret -ne 0 ] && return $ret
-
-    # Build jailer only in case of musl for compatibility reasons.
-    if [ "$libc" == "musl" ];then
-        say "No musl to build."
-
-    fi
-
-    ret=$?
-
-    # If `cargo build` was successful, output a message.
-    [ $ret -eq 0 ] && {
-        cargo_bin_dir="$CARGO_TARGET_DIR/$target/$profile"
-        seccompiler_bin_dir="$CARGO_SECCOMPILER_TARGET_DIR/$target/$profile"
-        rebase_snap_bin_dir="$CARGO_REBASE_SNAP_TARGET_DIR/$target/$profile"
-
-        # Seccompiler has a different build folder, we need to output two
-        # messages.
-        say "Build successful."
-        say "Firecracker and Jailer binaries placed under $cargo_bin_dir"
-        say "Seccompiler-bin binary placed under $seccompiler_bin_dir"
-        say "Rebase_snap binary placed under $rebase_snap_bin_dir"
-    }
-
-    return $ret
+cmd_serve() {
+    say "cmd_serve"
 }
 
 cmd_help() {
     echo ""
-    echo "Firecracker $(basename $0)"
-    echo "Usage: $(basename $0) [<args>] <command> [<command args>]"
-    echo ""
-    echo "Global arguments"
-    echo "    -y, --unattended         Run unattended. Assume the user would always"
-    echo "                             answer \"yes\" to any confirmation prompt."
-    echo ""
-    echo "Available commands:"
-    echo ""
-    echo "    build [--debug|--release] [-l|--libc musl|gnu] [-- [<cargo args>]]"
-    echo "        Build the Firecracker binaries."
-    echo "        Firecracker is built using the Rust build system (cargo). All arguments after --"
-    echo "        will be passed through to cargo."
-    echo "        --debug               Build the debug binaries. This is the default."
-    echo "        --release             Build the release binaries."
-    echo "        -l, --libc musl|gnu   Choose the libc flavor against which Firecracker will"
-    echo "                              be linked. Default is musl."
-    echo "        --ssh-keys            Provide the paths to the public and private SSH keys on the host"
-    echo "                              (in this particular order) required for the git authentication."
-    echo "                              It is mandatory that both keys are specified."
-    echo ""
-    echo "    build_devctr [--no-python-package-update]"
-    echo "        Builds the development container from its Dockerfile."
-    echo "        -n, --no-python-package-update  Do not update python packages."
-    echo ""
-    echo "    build_kernel -c|--config [-n|--nproc]"
-    echo "        Builds a kernel image custom-tailored for our CI."
-    echo "        -c, --config  Path to the config file."
-    echo "        -n, --nproc  Number of cores to use for building kernel."
-
-
-    echo "    build_rootfs -s|--size [--partuuid]"
-    echo "        Builds a rootfs image custom-tailored for use in our CI."
-    echo "        -s, --size      Size of the rootfs image. Defaults to 300MB.
-                                  The format is the same as that of 'truncates'."
-    echo "        -p, --partuuid  Whether to build a partuuid image."
-    echo ""
-    echo "    checkenv"
-    echo "        Performs prerequisites checks needed to execute firecracker."
-    echo ""
-    echo "    ci"
-    echo "        Run a continuous integration test run that executes the integration tests and"
-    echo "        checks that the release process works."
-    echo ""
-    echo "    create_snapshot_artifacts"
-    echo "        Runs a tool that generates snapshot artifacts for supported kernel versions."
-    echo "        Snapshot mem and state files are saved under \`snapshot_artifacts/\` directory"
-    echo ""
-    echo "    distclean"
-    echo "        Clean up the build tree and remove the docker container."
-    echo ""
-    echo "    fix_perms"
-    echo "        Fixes permissions when devtool dies in the middle of a privileged session."
-    echo ""
-    echo "    fmt"
-    echo "        Auto-format all Rust source files, to match the Firecracker requirements."
-    echo "        This should be used as the last step in every commit, to ensure that the"
-    echo "        Rust style tests pass."
-    echo ""
-    echo "    generate_syscall_tables <version>"
-    echo "        Generates the syscall tables for seccompiler, according to a given kernel version."
-    echo "        Release candidate (rc) linux versions are not allowed."
-    echo "        Outputs a rust file for each supported arch: src/seccompiler/src/syscall_table/{arch}.rs"
-    echo "        Supported architectures: x86_64 and aarch64."
-    echo ""
-    echo "    install [-p|--path] [--debug|--release]"
-    echo "      Install firecracker, jailer and seccomp binaries to /usr/local/bin or a given path."
-    echo "      Only the musl linked binaries are supported."
-    echo "        --path                Install binaries to a specified path."
-    echo "        --debug               Install the debug binaries."
-    echo "        --release             Install the release binaries. This is the default."
-    echo ""
-    echo "    help"
-    echo "        Display this help message."
-    echo ""
-    echo "    prepare_release <version>"
-    echo "        Prepare a new Firecracker release by updating the version number, crate "
-    echo "        dependencies and credits."
-    echo ""
-
-    echo ""
-    echo "    shell [--privileged]"
-    echo "        Launch the development container and open an interactive BASH shell."
-    echo "        -p, --privileged    Run the container as root, in privileged mode."
-    echo "                            Running Firecracker via the jailer requires elevated"
-    echo "                            privileges, though the build phase does not."
-    echo ""
-    echo "    tag <version>"
-    echo "        Create a git tag for the specified version. The tag message will contain "
-    echo "        the contents of CHANGELOG.md enclosed between the header corresponding to "
-    echo "        the specified version and the one corresponding to the previous version."
-    echo ""
-    echo "    test [-- [<pytest args>]]"
-    echo "        Run the Firecracker integration tests."
-    echo "        The Firecracker testing system is based on pytest. All arguments after --"
-    echo "        will be passed through to pytest."
-    echo "        -c, --cpuset-cpus cpulist    Set a dedicated cpulist to be used by the tests."
-    echo "        -m, --cpuset-mems memlist    Set a dedicated memlist to be used by the tests."
-    echo "        -r, --ramdisk size[k|m|g]    Use a ramdisk of `size` MB for
-                                               the entire test session (e.g
-                                               stored artifacts, Firecracker
-                                               binaries, logs/metrics FIFOs
-                                               and test created device files)."
-    echo ""
-    echo "    strip"
-    echo "        Strip debug symbols from the Firecracker release binaries."
+    echo "Vulcan $(basename $0)"
+    echo "not yet completed"
     echo ""
 }
 
@@ -483,7 +358,7 @@ main() {
     while [ $# -gt 0 ]; do
         case "$1" in
             -h|--help)              { cmd_help; exit 1;     } ;;
-            -y|--unattended)        { OPT_UNATTENDED=true;  } ;;
+            -m|--MM)                { say "--MM"; exit 1;  } ;;
             -*)
                 die "Unknown arg: $1. Please use \`$0 help\` for help."
             ;;
